//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBreak.Dato
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoEvento()
        {
            this.Contrato = new HashSet<Contrato>();
        }
    
        public int tipo_evento { get; set; }
        public string nombre_evento { get; set; }
        public int valor_base { get; set; }
        public int personal_base { get; set; }
        public int personal_adicional { get; set; }
        public int asistente_adicional { get; set; }
        public double valor_personal_adicional { get; set; }
        public int valor_asistente_adicional { get; set; }
        public double valor_total_evento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
    }
}
